name: OWASP ZAP Integration with GitHub Actions

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://testphp.vulnweb.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Save ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: /zap/wrk/

      - name: Report Scan Result
        if: failure()
        run: |
          echo "Vulnerabilities found during the scan. Failing the build."
          exit 1
